# Example compose file for the JMRI roster application stack.
version: "2.2"

services:
  
  api:
    image: tomhomewood/irelay-mqtt:latest
    container_name: irelay-mqtt
    restart: unless-stopped
    cpu_count: 2
    mem_limit: 256m
    network_mode: "host"
