# Example compose file for the JMRI roster application stack.
version: "2.2"
services:
  irelay-api:
    image: tomhomewood/irelay-mqtt:latest
    container_name: irelay-mqtt
    restart: unless-stopped
    environment:
      - MQTT_ENDPOINT=<broker_address_or_hostname>
      - MQTT_PORT=<broker_port>
      - MQTT_CLIENT_ID=irelay_mqtt
      - MQTT_USERNAME=<username>
      - MQTT_PASSWORD=<password>
      - GRAVITY_OFFSET_ISPINDEL_CHANNEL_1=-.006
      - ROUND_VALUES=true
    network_mode: "host"
